In [1]:
import tensorflow as tf 
import os
import numpy as np 

os.environ['TF_CPP_MIN_LOG_LEVEL']='2'

In [2]:
B = tf.constant([[1.,2.,3],[4,5,6],[7,8,9]])

print(f"B = {B}")

B = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [3]:
print(f"B.shape = {B.shape}")
print(f"B.dtype = {B.dtype}")

B.shape = (3, 3)
B.dtype = <dtype: 'float32'>


In [5]:
print(f"B[:,:] = {B[:,:]}") 



B[:,:] = [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [17]:
print(f"{B[1:,:2]}")

[[4. 5.]
 [7. 8.]]


In [18]:
print(f"B+100 =\n {B+100}")

B+100 =
 [[101. 102. 103.]
 [104. 105. 106.]
 [107. 108. 109.]]


In [19]:
print(f"B+100 =\n {tf.add(B,100)}")  


B+100 =
 [[101. 102. 103.]
 [104. 105. 106.]
 [107. 108. 109.]]


In [50]:
np_array_1 = np.array([1.,2.,3.,4.,5.,6.,7.,8.,9.,10.])
tf_tensor = tf.constant(np_array_1)
print("np_array_1 :", np_array_1)
print("tf_tensor : ",tf_tensor) 

np_array_1 : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
tf_tensor :  tf.Tensor([ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.], shape=(10,), dtype=float64)


In [23]:
np_array_2 = tf_tensor.numpy()
print("np_array_2 : ", np_array_2) 

np_array_2 :  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [33]:
a=tf.constant(10., dtype="float64")
b = tf.constant(10.) 
#print(f"a+b = {a+b}") #cette instruction va afficher une erreur à l'exécution

In [34]:
a=tf.constant(10., dtype="float64")
b = tf.constant(10.) 

a=tf.cast(a, tf.float32 )
print(f"a+b = {a+b}")


a+b = 20.0


In [36]:
tensor_1 = tf.Variable([[1,2,3],[4,5,6],[7,8,9]])
 
print(f"tensor_1 = \n{tensor_1}")

tensor_1.assign(tensor_1 * 100)
print(f"tensor_1 = \n{tensor_1}")

tensor_1 = 
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>
tensor_1 = 
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[100, 200, 300],
       [400, 500, 600],
       [700, 800, 900]])>


In [42]:
tensor_2 = tf.zeros((3,3))
print(f"tensor_2 = \n{tensor_2}")

tensor_2 = 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [43]:
tensor_3 = tf.random.uniform((4,4), minval=1, maxval=100, seed=1)
print(f"tensor_3 = \n{tensor_3}")

tensor_3 = 
[[58.47219   95.02471   45.46765    2.750136 ]
 [97.74797    8.634356  21.857983  53.07471  ]
 [ 3.2755132 38.687164  16.020048  63.995255 ]
 [47.905804  89.088806  12.25897   50.965908 ]]


In [44]:
tensor_4 = tf.fill((3,3), value = 5) 
print(f"tensor_4 = \n{tensor_4}")

tensor_4 = 
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [47]:
tensor_5 = tf.fill((2,3), 1) 
tensor_6 = tf.fill((3,2), 2) 
print(f"tensor_5 = \n{tensor_5}")
print(f"tensor_6 = \n{tensor_6}")

tensor_7 = tf.matmul(tensor_5, tensor_6)
print(f"tensor_7 = \n{tensor_7}")

tensor_5 = 
[[1 1 1]
 [1 1 1]]
tensor_6 = 
[[2 2]
 [2 2]
 [2 2]]
tensor_7 = 
[[6 6]
 [6 6]]
